## Builder stage
FROM node:25-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY . .

## Image stage
FROM node:25-alpine
WORKDIR /app
COPY --from=builder /app /app
EXPOSE 3000
USER node
CMD ["node", "app.js"]